# https://taskfile.dev

version: '3'

tasks:

  default:
    # deps: [pixiectl, basic]
    deps: [pixiectl]

  pixiectl:
    cmds:
      - go build -o bin/{{.TASK}} ./cmd/{{.TASK}}/
      
  pixiectl-run:
    cmds:
      - go run ./cmd/{{.TASK | replace "-run" ""}}/
      
  # basic:
  #   cmds:
  #     - go build -o bin/{{.TASK}} cmd/{{.TASK}}/

  # basic-run:
  #   cmds:
  #     - go run cmd/{{.TASK | replace "-run" ""}}/
      
